// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('平日-２泊-朝食なし', async function() {
    await driver.get("http://example.selenium.jp/reserveApp_Renewal/")
    await driver.manage().window().setRect(1920, 1057)
    await driver.findElement(By.id("datePick")).click()
    await driver.findElement(By.css(".datepicker-days .prev")).click()
    await driver.findElement(By.css(".datepicker-days .prev")).click()
    await driver.findElement(By.css(".datepicker-days .prev")).click()
    {
      const element = await driver.findElement(By.css(".datepicker-days .prev"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".datepicker-days .prev")).click()
    await driver.findElement(By.id("datePick")).click()
    await driver.findElement(By.id("datePick")).click()
    await driver.findElement(By.id("datePick")).click()
    await driver.findElement(By.id("datePick")).sendKeys("2018/12/17")
    await driver.findElement(By.css(".active:nth-child(2)")).click()
    await driver.findElement(By.id("reserve_term")).click()
    {
      const dropdown = await driver.findElement(By.id("reserve_term"))
      await dropdown.findElement(By.xpath("//option[. = '2']")).click()
    }
    await driver.findElement(By.id("breakfast_off")).click()
    await driver.findElement(By.id("guestname")).click()
    await driver.findElement(By.id("guestname")).sendKeys("山田一郎")
    await driver.findElement(By.id("agree_and_goto_next")).click()
    await driver.findElement(By.id("returnto_index")).click()
    await driver.findElement(By.id("datePick")).click()
    await driver.findElement(By.css("tr:nth-child(3) > .day:nth-child(6)")).click()
    await driver.findElement(By.id("reserve_info")).click()
    await driver.findElement(By.id("agree_and_goto_next")).click()
    await driver.findElement(By.id("price")).click()
    assert(await driver.findElement(By.id("price")).getText() == "14000")
    await driver.close()
  })
})