// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test3', async function() {
    // Test name: Test3
    // Step # | name | target | value
    // 1 | open | http://example.selenium.jp/reserveApp_Renewal/ | 
    await driver.get("http://example.selenium.jp/reserveApp_Renewal/")
    // 2 | setWindowSize | 1920x1057 | 
    await driver.manage().window().setRect(1920, 1057)
    // 3 | click | id=datePick | 
    await driver.findElement(By.id("datePick")).click()
    // 4 | click | css=.new:nth-child(2) | 
    await driver.findElement(By.css(".new:nth-child(2)")).click()
    // 5 | click | id=reserve_term | 
    await driver.findElement(By.id("reserve_term")).click()
    // 6 | select | id=reserve_term | label=2
    {
      const dropdown = await driver.findElement(By.id("reserve_term"))
      await dropdown.findElement(By.xpath("//option[. = '2']")).click()
    }
    // 7 | click | id=breakfast_off | 
    await driver.findElement(By.id("breakfast_off")).click()
    // 8 | click | id=guestname | 
    await driver.findElement(By.id("guestname")).click()
    // 9 | type | id=guestname | 山田一郎
    await driver.findElement(By.id("guestname")).sendKeys("山田一郎")
    // 10 | click | id=agree_and_goto_next | 
    await driver.findElement(By.id("agree_and_goto_next")).click()
    // 11 | click | id=total | 
    await driver.findElement(By.id("total")).click()
    // 12 | assertText | id=price | 14000
    assert(await driver.findElement(By.id("price")).getText() == "14000")
  })
})
